#!/bin/bash
# ---------------------------------------------------------------------------
# Build no-op stand-ins for OPTIONAL shared libraries that a bundled binary
# links against but that the bundle does not ship for this architecture.
#
# Why this is needed: the bundle installs Ubuntu's libcurl (libcurl3t64-gnutls),
# which has DT_NEEDED entries for libssh / libldap / liblber. Those are only
# used for scp://, sftp:// and ldap:// URLs, but the dynamic loader refuses to
# start ANY consumer when they are absent -- which takes out git-over-HTTPS and
# curl entirely.
#
# The stubs export exactly the symbols (and symbol versions) the consumer
# imports, and return 0. HTTPS/FTP keep working; the SSH and LDAP URL schemes
# do not. Nothing is overwritten: stubs go to their own directory, which is
# appended to the loader search path.
#
# Usage: stub-missing-libs.sh [outdir] [consumer-elf ...]
# ---------------------------------------------------------------------------
set -euo pipefail

OUT="${1:-/usr/local/lib/offline-bundle-stubs}"
shift || true
CONSUMERS=("$@")
if [ ${#CONSUMERS[@]} -eq 0 ]; then
    CONSUMERS=(/usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 /usr/lib/x86_64-linux-gnu/libcurl.so.4)
fi

SUDO=""; [ "$(id -u)" -ne 0 ] && SUDO="sudo"
TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT

# Which optional libraries do we know how to stub, and which symbol prefixes
# belong to each?
stub_for() {
    case "$1" in
        libssh.so.*)  echo '^(ssh_|sftp_)' ;;
        libldap*.so.*|libldap.so.*) echo '^ldap_' ;;
        liblber.so.*) echo '^(ber_|lber_)' ;;
        *) return 1 ;;
    esac
}

declare -A MISSING=()
for c in "${CONSUMERS[@]}"; do
    [ -e "$c" ] || continue
    while read -r lib; do
        [ -n "$lib" ] && MISSING["$lib"]="${MISSING[$lib]:-} $c"
    done < <(ldd "$c" 2>/dev/null | awk '/not found/{print $1}')
done

[ ${#MISSING[@]} -eq 0 ] && { echo "  no missing optional libraries"; exit 0; }

built=0
for lib in "${!MISSING[@]}"; do
    pat=$(stub_for "$lib") || { echo "  skip $lib (not a known optional library)"; continue; }

    : > "$TMP/sel.txt"
    for c in ${MISSING[$lib]}; do
        nm -D --undefined-only "$c" 2>/dev/null | sed 's/^ *U *//' | grep -E "$pat" || true
    done | sort -u > "$TMP/sel.txt"
    [ -s "$TMP/sel.txt" ] || { echo "  skip $lib (no symbols referenced)"; continue; }

    # Functions that report a version string must hand back a valid pointer,
    # otherwise callers such as `curl --version` dereference NULL.
    { echo '/* generated by tools/stub-missing-libs.sh - do not edit */'
      echo 'static const char _stub_empty[] = "";'
      sed 's/@.*//' "$TMP/sel.txt" | sort -u | while read -r s; do
          case "$s" in
              *version*|*_str|*_strerror|*err2string)
                  echo "const char *$s(void){ return _stub_empty; }" ;;
              *get_option*)
                  # report failure, so callers do not read uninitialised out-params
                  echo "long $s(void){ return -1; }" ;;
              *)  echo "long $s(void){ return 0; }" ;;
          esac
      done
    } > "$TMP/stub.c"

    : > "$TMP/ver.map"
    for v in $(sed -n 's/.*@@\?//p' "$TMP/sel.txt" | sort -u); do
        { echo "$v {"; echo "  global:"
          grep -E "@@?${v}\$" "$TMP/sel.txt" | sed 's/@.*//' | sort -u | sed 's/^/    /; s/$/;/'
          echo "  local: *;"; echo "};"
        } >> "$TMP/ver.map"
    done

    $SUDO mkdir -p "$OUT"
    if [ -s "$TMP/ver.map" ]; then
        $SUDO gcc -shared -fPIC -o "$OUT/$lib" "$TMP/stub.c" \
              -Wl,-soname,"$lib" -Wl,--version-script="$TMP/ver.map"
    else
        $SUDO gcc -shared -fPIC -o "$OUT/$lib" "$TMP/stub.c" -Wl,-soname,"$lib"
    fi
    echo "  built stub $lib ($(wc -l < "$TMP/sel.txt") symbols)"
    built=$((built+1))
done

if [ $built -gt 0 ]; then
    echo "$OUT" | $SUDO tee /etc/ld.so.conf.d/zz-offline-bundle-stubs.conf >/dev/null
    $SUDO ldconfig
    echo "  registered $OUT with ldconfig"
fi
